apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: k8s-gitops-lab
  namespace: argocd
spec:
  description: "K8s GitOps Lab - All applications"
  sourceRepos:
  - '*'
  destinations:
  - namespace: '*'
    server: https://kubernetes.default.svc
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'
