apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: monitoring
resources:
- https://github.com/prometheus-community/helm-charts/releases/download/kube-prometheus-stack-61.9.0/kube-prometheus-stack-61.9.0.tgz
patches:
- patch: |
    apiVersion: v1
    kind: Service
    metadata:
      name: prometheus-grafana
      namespace: monitoring
    spec:
      type: NodePort
      ports:
      - port: 80
        targetPort: 3000
        nodePort: 30300
  target:
    kind: Service
    name: prometheus-grafana
