apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: external-secrets
resources:
- https://github.com/external-secrets/external-secrets/releases/download/v0.10.0/external-secrets.yaml
